# Don't edit
version: 1.0.0
# Debug mode enables teleporting to self
debug: false

# request-time = 1000 millis = 1 sec
settings:
  request-time: 30000
  teleport-time: 0
  cancel-on-teleport-movement: true