# request-time = 1000 millis = 1 sec
settings:
  request-time: 30000
  teleport-time: 3000
  cancel-on-teleport-movement: true
  player-only-command: "<red>Only players can use this command!";
teleport-accepted:
  teleport-every-second:
    enabled: true
    message: "<yellow>Teleporting to <white>%who%</white> in <white>%second%</white>."
  teleporting: "<yellow>Teleporting to <white>%who%</white>..."
request-canceled:
  request-denied: "<red>Your teleport request to <white>%who%</white> was denied."
  requested-left: "<red><white>%who%</white> left teleport request canceled."
  sender-left: "<red><white>%who%</white> left the server their teleport request was denied."
  time-ran-out-sender: "<red>Your teleport request to <white>%who%</white> has ran out of time."
  time-ran-out-requested: "<red><white>%who%</white>'s teleport request to you has ran out of time."
  moved: "<red>You moved. you are no longer teleporting to <white>%who%</white>."
commands:
  tpa:
    cooldown: 0
    description: "Allows player to teleport to given player."
    usage: "/tpa <online player>"
    aliases: ["tpask"]
    incorrect-format: "<red>Incorrect Usage! <gray>/tpa <online player>"
    unknown-player: "<red>Incorrect Usage! <gray>/tpa <online player>"
    blocked: "<red><white>%who%</white> has blocked you. You cannot send requests to them.</red>"
    request-already-sent: "<red>You have already sent a teleport request to <white>%who%</white>."
    sent-sender: "<green>Sent teleport request to <white>%who%</white>!</green>"
    sent-requested: "<green>You received teleport request from <white>%who%</white>! <click:run_command:/tpaccept %who%><green><bold>ACCEPT</bold></click> <click:run_command:/tpdeny %who%><red><bold>DENY</bold></click></green>"
  tpaccept:
    cooldown: 0
    description: "Allows player to accept teleport of given player."
    usage: "/tpaccept <online player>"
    aliases: ["tpaccept"]
    incorrect-format: "<red>Incorrect Usage! <gray>/tpaccept <online player>"
    unknown-player: "<red>Incorrect Usage! <gray>/tpaccept <online player>"
    no-request-found: "<red>Could not find any teleport requests from <white>%who%</white>!</green>"
    accepted-sender: "<green>Your teleport request to <white>%who%</white> has been ACCEPTED!</green>"
    accepted-requested: "<green>Accepted teleport request of <white>%who%</white>!</green>"
  tpdeny:
    cooldown: 0
    description: "Allows player to deny teleport of given player."
    usage: "/tpa <online player>"
    aliases: ["tpdeny"]
    incorrect-format: "<red>Incorrect Usage! <gray>/tpaccept <online player>"
    unknown-player: "<red>Incorrect Usage! <gray>/tpaccept <online player>"
    no-request-found: "<red>Could not find any teleport requests from <white>%who%</white>!</green>"
    denied-sender: "<red>Your teleport request to <white>%who%</white> has been DENIED!</red>"
    denied-requested: "<green>You denied teleport request of <white>%who%</white>!</green>"
  tpblock:
    cooldown: 0
    description: "Allows player to unblock teleport requests of given player."
    usage: "/tpblock <online player>"
    aliases: ["tpignore"]
    incorrect-format: "<red>Incorrect Usage! <gray>/tpaccept <online player>"
    unknown-player: "<red>Incorrect Usage! <gray>/tpaccept <online player>"
    no-request-found: "<red>Could not find any teleport requests from <white>%who%</white>!</green>"
    blocked-sender: "<green>Blocked <white>%who%</white> from sending teleports to you!</green>"
    blocked-user: "<red>You can no longer send teleport requests to <white>%who%</white>!</red>"
  tpunblock:
    cooldown: 0
    description: "Allows player to unblock teleport requests of given player."
    usage: "/tpunblock <online player>"
    aliases: ["tpunignore"]
    incorrect-format: "<red>Incorrect Usage! <gray>/tpaccept <online player>"
    unknown-player: "<red>Incorrect Usage! <gray>/tpaccept <online player>"
    no-request-found: "<red>Could not find any teleport requests from <white>%who%</white>!</green>"
    request-sent: "<green>Unblocked <white>%who%</white> from sending teleports to you!</green>"
    unblocked-sender: "<green>Unblocked <white>%who%</white> from sending teleports to you!</green>"
    unblocked-user: "<red>You can now send teleport requests to <white>%who%</white>!</red>"
  tptoggle:
    cooldown: 0
    description: "Allows player toggle between receiving and not receiving ."
    usage: "/tptoggle"
    aliases: []
    no-request-found: "<red>Could not find any teleport requests from <white>%who%</white>!</green>"
    toggled-on: "<red>You will no longer receive teleport requests.</red>"
    toggled-off: "<green>You will now receive teleport requests.</green>"